<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
  use HasFactory;

  protected $table    = 'categories';
  protected $fillable = ['title', 'slug'];

  public function products()
  {
    return $this->hasMany(Product::class);
  }

  protected static function boot()
  {
    parent::boot(); // TODO: Change the autogenerated stub
    static::saving(function ($category) {
      $category->slug = Str::slug($category->title);
    });
  }
}
