<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Tag extends Model
{
  use HasFactory;

  protected $table    = 'tags';
  protected $fillable = ['title', 'slug'];

  public function product()
  {
    return $this->belongsToMany(Product::class, 'product_tag');
  }

  protected static function boot()
  {
    parent::boot(); // TODO: Change the autogenerated stub
    static::saving(function ($tag) {
      $tag->slug = Str::slug($tag->title);
    });
  }
}
